/// @description Insert description here
// You can write your code in this editor
if(hp<1){
	instance_destroy();
	with(hearingBubble){
		instance_destroy();
	}
}
if(alert==50){
	//Attack at alert spot
	var inst = instance_find(oPlayer,0);
	attackSpotX=inst.x;
	attackSpotY=inst.y;
	attackVelX=(attackSpotX-x)/5;
	attackVelY=(attackSpotY-y)/5;
	if(attackSpotY<y+160&&attackSpotY>y-32){
		action=1;
	}
	else{
		action=3;
	}
}
else if(alert<40&&alert>35){
	if(action==1){
		x+=attackVelX;
		//y+=attackVelY;
	}
	else{
		for(j=0;j<5;j++){
			inst=instance_create_depth(x,y,0,oQuill);
			with(inst){
				xVel=other.attackVelX*2-9+irandom(5);
				yVel=other.attackVelY*2-9+irandom(5);
				y=other.y-other.sprite_height/2;
			}
		}
	}
}
else{
	lastx=x;
	lasty=y;
	x=x+spd/2.0-random(spd);
	if(tilemap_get_at_pixel(oGame.map,x-(sprite_get_width(sprite_index)/2),y-1)==3){
		x=lastx;
		y=lasty;
	}
	if(tilemap_get_at_pixel(oGame.map,x+(sprite_get_width(sprite_index)/2),y-1)==3){
		x=lastx;
		y=lasty;
	}
	if(tilemap_get_at_pixel(oGame.map,x,y+sprite_get_height(sprite_index))==3){
		x=lastx;
		y=lasty;
	}
	if(tilemap_get_at_pixel(oGame.map,x,y-sprite_get_height(sprite_index))==3){
		x=lastx;
		y=lasty;
	}
}
alert--;